// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.1
// source: api/proto/mikrotik.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MikroTikServiceClient is the client API for MikroTikService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MikroTikServiceClient interface {
	GetPPPoEActive(ctx context.Context, in *GetPPPoEActiveRequest, opts ...grpc.CallOption) (*PPPoEUsers, error)
	GetPPPoEUser(ctx context.Context, in *GetPPPoEUserRequest, opts ...grpc.CallOption) (*PPPoEUser, error)
	CreatePPPoEUser(ctx context.Context, in *CreatePPPoEUserRequest, opts ...grpc.CallOption) (*Response, error)
	UpdatePPPoEUser(ctx context.Context, in *UpdatePPPoEUserRequest, opts ...grpc.CallOption) (*PPPoEUser, error)
	RemovePPPoEUser(ctx context.Context, in *RemovePPPoEUserRequest, opts ...grpc.CallOption) (*Response, error)
	CheckConnection(ctx context.Context, in *CheckConnectionRequest, opts ...grpc.CallOption) (*Response, error)
}

type mikroTikServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMikroTikServiceClient(cc grpc.ClientConnInterface) MikroTikServiceClient {
	return &mikroTikServiceClient{cc}
}

func (c *mikroTikServiceClient) GetPPPoEActive(ctx context.Context, in *GetPPPoEActiveRequest, opts ...grpc.CallOption) (*PPPoEUsers, error) {
	out := new(PPPoEUsers)
	err := c.cc.Invoke(ctx, "/mikrotik.MikroTikService/GetPPPoEActive", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mikroTikServiceClient) GetPPPoEUser(ctx context.Context, in *GetPPPoEUserRequest, opts ...grpc.CallOption) (*PPPoEUser, error) {
	out := new(PPPoEUser)
	err := c.cc.Invoke(ctx, "/mikrotik.MikroTikService/GetPPPoEUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mikroTikServiceClient) CreatePPPoEUser(ctx context.Context, in *CreatePPPoEUserRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/mikrotik.MikroTikService/CreatePPPoEUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mikroTikServiceClient) UpdatePPPoEUser(ctx context.Context, in *UpdatePPPoEUserRequest, opts ...grpc.CallOption) (*PPPoEUser, error) {
	out := new(PPPoEUser)
	err := c.cc.Invoke(ctx, "/mikrotik.MikroTikService/UpdatePPPoEUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mikroTikServiceClient) RemovePPPoEUser(ctx context.Context, in *RemovePPPoEUserRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/mikrotik.MikroTikService/RemovePPPoEUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mikroTikServiceClient) CheckConnection(ctx context.Context, in *CheckConnectionRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/mikrotik.MikroTikService/CheckConnection", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MikroTikServiceServer is the server API for MikroTikService service.
// All implementations must embed UnimplementedMikroTikServiceServer
// for forward compatibility
type MikroTikServiceServer interface {
	GetPPPoEActive(context.Context, *GetPPPoEActiveRequest) (*PPPoEUsers, error)
	GetPPPoEUser(context.Context, *GetPPPoEUserRequest) (*PPPoEUser, error)
	CreatePPPoEUser(context.Context, *CreatePPPoEUserRequest) (*Response, error)
	UpdatePPPoEUser(context.Context, *UpdatePPPoEUserRequest) (*PPPoEUser, error)
	RemovePPPoEUser(context.Context, *RemovePPPoEUserRequest) (*Response, error)
	CheckConnection(context.Context, *CheckConnectionRequest) (*Response, error)
	mustEmbedUnimplementedMikroTikServiceServer()
}

// UnimplementedMikroTikServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMikroTikServiceServer struct {
}

func (UnimplementedMikroTikServiceServer) GetPPPoEActive(context.Context, *GetPPPoEActiveRequest) (*PPPoEUsers, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPPPoEActive not implemented")
}
func (UnimplementedMikroTikServiceServer) GetPPPoEUser(context.Context, *GetPPPoEUserRequest) (*PPPoEUser, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPPPoEUser not implemented")
}
func (UnimplementedMikroTikServiceServer) CreatePPPoEUser(context.Context, *CreatePPPoEUserRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePPPoEUser not implemented")
}
func (UnimplementedMikroTikServiceServer) UpdatePPPoEUser(context.Context, *UpdatePPPoEUserRequest) (*PPPoEUser, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePPPoEUser not implemented")
}
func (UnimplementedMikroTikServiceServer) RemovePPPoEUser(context.Context, *RemovePPPoEUserRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemovePPPoEUser not implemented")
}
func (UnimplementedMikroTikServiceServer) CheckConnection(context.Context, *CheckConnectionRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckConnection not implemented")
}
func (UnimplementedMikroTikServiceServer) mustEmbedUnimplementedMikroTikServiceServer() {}

// UnsafeMikroTikServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MikroTikServiceServer will
// result in compilation errors.
type UnsafeMikroTikServiceServer interface {
	mustEmbedUnimplementedMikroTikServiceServer()
}

func RegisterMikroTikServiceServer(s grpc.ServiceRegistrar, srv MikroTikServiceServer) {
	s.RegisterService(&MikroTikService_ServiceDesc, srv)
}

func _MikroTikService_GetPPPoEActive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPPPoEActiveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MikroTikServiceServer).GetPPPoEActive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mikrotik.MikroTikService/GetPPPoEActive",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MikroTikServiceServer).GetPPPoEActive(ctx, req.(*GetPPPoEActiveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MikroTikService_GetPPPoEUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPPPoEUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MikroTikServiceServer).GetPPPoEUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mikrotik.MikroTikService/GetPPPoEUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MikroTikServiceServer).GetPPPoEUser(ctx, req.(*GetPPPoEUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MikroTikService_CreatePPPoEUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePPPoEUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MikroTikServiceServer).CreatePPPoEUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mikrotik.MikroTikService/CreatePPPoEUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MikroTikServiceServer).CreatePPPoEUser(ctx, req.(*CreatePPPoEUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MikroTikService_UpdatePPPoEUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePPPoEUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MikroTikServiceServer).UpdatePPPoEUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mikrotik.MikroTikService/UpdatePPPoEUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MikroTikServiceServer).UpdatePPPoEUser(ctx, req.(*UpdatePPPoEUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MikroTikService_RemovePPPoEUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemovePPPoEUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MikroTikServiceServer).RemovePPPoEUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mikrotik.MikroTikService/RemovePPPoEUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MikroTikServiceServer).RemovePPPoEUser(ctx, req.(*RemovePPPoEUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MikroTikService_CheckConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckConnectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MikroTikServiceServer).CheckConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mikrotik.MikroTikService/CheckConnection",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MikroTikServiceServer).CheckConnection(ctx, req.(*CheckConnectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MikroTikService_ServiceDesc is the grpc.ServiceDesc for MikroTikService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MikroTikService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mikrotik.MikroTikService",
	HandlerType: (*MikroTikServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPPPoEActive",
			Handler:    _MikroTikService_GetPPPoEActive_Handler,
		},
		{
			MethodName: "GetPPPoEUser",
			Handler:    _MikroTikService_GetPPPoEUser_Handler,
		},
		{
			MethodName: "CreatePPPoEUser",
			Handler:    _MikroTikService_CreatePPPoEUser_Handler,
		},
		{
			MethodName: "UpdatePPPoEUser",
			Handler:    _MikroTikService_UpdatePPPoEUser_Handler,
		},
		{
			MethodName: "RemovePPPoEUser",
			Handler:    _MikroTikService_RemovePPPoEUser_Handler,
		},
		{
			MethodName: "CheckConnection",
			Handler:    _MikroTikService_CheckConnection_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/mikrotik.proto",
}
