// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.1
// source: api/proto/mikrotik.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Connection struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Host string `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	User string `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Pass string `protobuf:"bytes,3,opt,name=pass,proto3" json:"pass,omitempty"`
}

func (x *Connection) Reset() {
	*x = Connection{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_mikrotik_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Connection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Connection) ProtoMessage() {}

func (x *Connection) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_mikrotik_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Connection.ProtoReflect.Descriptor instead.
func (*Connection) Descriptor() ([]byte, []int) {
	return file_api_proto_mikrotik_proto_rawDescGZIP(), []int{0}
}

func (x *Connection) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Connection) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *Connection) GetPass() string {
	if x != nil {
		return x.Pass
	}
	return ""
}

type GetPPPoEActiveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Conn *Connection `protobuf:"bytes,1,opt,name=conn,proto3" json:"conn,omitempty"`
}

func (x *GetPPPoEActiveRequest) Reset() {
	*x = GetPPPoEActiveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_mikrotik_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPPPoEActiveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPPPoEActiveRequest) ProtoMessage() {}

func (x *GetPPPoEActiveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_mikrotik_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPPPoEActiveRequest.ProtoReflect.Descriptor instead.
func (*GetPPPoEActiveRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_mikrotik_proto_rawDescGZIP(), []int{1}
}

func (x *GetPPPoEActiveRequest) GetConn() *Connection {
	if x != nil {
		return x.Conn
	}
	return nil
}

type GetPPPoEUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Conn *Connection `protobuf:"bytes,1,opt,name=conn,proto3" json:"conn,omitempty"`
	Name string      `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *GetPPPoEUserRequest) Reset() {
	*x = GetPPPoEUserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_mikrotik_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPPPoEUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPPPoEUserRequest) ProtoMessage() {}

func (x *GetPPPoEUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_mikrotik_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPPPoEUserRequest.ProtoReflect.Descriptor instead.
func (*GetPPPoEUserRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_mikrotik_proto_rawDescGZIP(), []int{2}
}

func (x *GetPPPoEUserRequest) GetConn() *Connection {
	if x != nil {
		return x.Conn
	}
	return nil
}

func (x *GetPPPoEUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreatePPPoEUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Conn     *Connection `protobuf:"bytes,1,opt,name=conn,proto3" json:"conn,omitempty"`
	Name     string      `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Password string      `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Profile  string      `protobuf:"bytes,4,opt,name=profile,proto3" json:"profile,omitempty"`
}

func (x *CreatePPPoEUserRequest) Reset() {
	*x = CreatePPPoEUserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_mikrotik_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePPPoEUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePPPoEUserRequest) ProtoMessage() {}

func (x *CreatePPPoEUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_mikrotik_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePPPoEUserRequest.ProtoReflect.Descriptor instead.
func (*CreatePPPoEUserRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_mikrotik_proto_rawDescGZIP(), []int{3}
}

func (x *CreatePPPoEUserRequest) GetConn() *Connection {
	if x != nil {
		return x.Conn
	}
	return nil
}

func (x *CreatePPPoEUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreatePPPoEUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreatePPPoEUserRequest) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

type UpdatePPPoEUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Conn           *Connection       `protobuf:"bytes,1,opt,name=conn,proto3" json:"conn,omitempty"`
	Name           string            `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	FieldsToUpdate map[string]string `protobuf:"bytes,3,rep,name=fields_to_update,json=fieldsToUpdate,proto3" json:"fields_to_update,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *UpdatePPPoEUserRequest) Reset() {
	*x = UpdatePPPoEUserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_mikrotik_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePPPoEUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePPPoEUserRequest) ProtoMessage() {}

func (x *UpdatePPPoEUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_mikrotik_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePPPoEUserRequest.ProtoReflect.Descriptor instead.
func (*UpdatePPPoEUserRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_mikrotik_proto_rawDescGZIP(), []int{4}
}

func (x *UpdatePPPoEUserRequest) GetConn() *Connection {
	if x != nil {
		return x.Conn
	}
	return nil
}

func (x *UpdatePPPoEUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdatePPPoEUserRequest) GetFieldsToUpdate() map[string]string {
	if x != nil {
		return x.FieldsToUpdate
	}
	return nil
}

type RemovePPPoEUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Conn *Connection `protobuf:"bytes,1,opt,name=conn,proto3" json:"conn,omitempty"`
	Name string      `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *RemovePPPoEUserRequest) Reset() {
	*x = RemovePPPoEUserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_mikrotik_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemovePPPoEUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemovePPPoEUserRequest) ProtoMessage() {}

func (x *RemovePPPoEUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_mikrotik_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemovePPPoEUserRequest.ProtoReflect.Descriptor instead.
func (*RemovePPPoEUserRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_mikrotik_proto_rawDescGZIP(), []int{5}
}

func (x *RemovePPPoEUserRequest) GetConn() *Connection {
	if x != nil {
		return x.Conn
	}
	return nil
}

func (x *RemovePPPoEUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CheckConnectionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Conn *Connection `protobuf:"bytes,1,opt,name=conn,proto3" json:"conn,omitempty"`
}

func (x *CheckConnectionRequest) Reset() {
	*x = CheckConnectionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_mikrotik_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckConnectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckConnectionRequest) ProtoMessage() {}

func (x *CheckConnectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_mikrotik_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckConnectionRequest.ProtoReflect.Descriptor instead.
func (*CheckConnectionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_mikrotik_proto_rawDescGZIP(), []int{6}
}

func (x *CheckConnectionRequest) GetConn() *Connection {
	if x != nil {
		return x.Conn
	}
	return nil
}

type PPPoEUser struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Attributes map[string]string `protobuf:"bytes,1,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *PPPoEUser) Reset() {
	*x = PPPoEUser{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_mikrotik_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PPPoEUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PPPoEUser) ProtoMessage() {}

func (x *PPPoEUser) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_mikrotik_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PPPoEUser.ProtoReflect.Descriptor instead.
func (*PPPoEUser) Descriptor() ([]byte, []int) {
	return file_api_proto_mikrotik_proto_rawDescGZIP(), []int{7}
}

func (x *PPPoEUser) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type PPPoEUsers struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Users []*PPPoEUser `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
}

func (x *PPPoEUsers) Reset() {
	*x = PPPoEUsers{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_mikrotik_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PPPoEUsers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PPPoEUsers) ProtoMessage() {}

func (x *PPPoEUsers) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_mikrotik_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PPPoEUsers.ProtoReflect.Descriptor instead.
func (*PPPoEUsers) Descriptor() ([]byte, []int) {
	return file_api_proto_mikrotik_proto_rawDescGZIP(), []int{8}
}

func (x *PPPoEUsers) GetUsers() []*PPPoEUser {
	if x != nil {
		return x.Users
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_mikrotik_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_mikrotik_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_api_proto_mikrotik_proto_rawDescGZIP(), []int{9}
}

func (x *Response) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_proto_mikrotik_proto protoreflect.FileDescriptor

var file_api_proto_mikrotik_proto_rawDesc = []byte{
	0x0a, 0x18, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x69, 0x6b, 0x72,
	0x6f, 0x74, 0x69, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x6d, 0x69, 0x6b, 0x72,
	0x6f, 0x74, 0x69, 0x6b, 0x22, 0x48, 0x0a, 0x0a, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61,
	0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x73, 0x73, 0x22, 0x41,
	0x0a, 0x15, 0x47, 0x65, 0x74, 0x50, 0x50, 0x50, 0x6f, 0x45, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x04, 0x63, 0x6f, 0x6e, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6d, 0x69, 0x6b, 0x72, 0x6f, 0x74, 0x69, 0x6b,
	0x2e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x04, 0x63, 0x6f, 0x6e,
	0x6e, 0x22, 0x53, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x50, 0x50, 0x50, 0x6f, 0x45, 0x55, 0x73, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x04, 0x63, 0x6f, 0x6e, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6d, 0x69, 0x6b, 0x72, 0x6f, 0x74, 0x69,
	0x6b, 0x2e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x04, 0x63, 0x6f,
	0x6e, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x8c, 0x01, 0x0a, 0x16, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x50, 0x50, 0x50, 0x6f, 0x45, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x28, 0x0a, 0x04, 0x63, 0x6f, 0x6e, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x14, 0x2e, 0x6d, 0x69, 0x6b, 0x72, 0x6f, 0x74, 0x69, 0x6b, 0x2e, 0x43, 0x6f, 0x6e, 0x6e, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x04, 0x63, 0x6f, 0x6e, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x70,
	0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x72,
	0x6f, 0x66, 0x69, 0x6c, 0x65, 0x22, 0xf9, 0x01, 0x0a, 0x16, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x50, 0x50, 0x50, 0x6f, 0x45, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x28, 0x0a, 0x04, 0x63, 0x6f, 0x6e, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14,
	0x2e, 0x6d, 0x69, 0x6b, 0x72, 0x6f, 0x74, 0x69, 0x6b, 0x2e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x04, 0x63, 0x6f, 0x6e, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x5e,
	0x0a, 0x10, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x5f, 0x74, 0x6f, 0x5f, 0x75, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x34, 0x2e, 0x6d, 0x69, 0x6b, 0x72, 0x6f,
	0x74, 0x69, 0x6b, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x50, 0x50, 0x6f, 0x45, 0x55,
	0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64,
	0x73, 0x54, 0x6f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0e,
	0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x54, 0x6f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x1a, 0x41,
	0x0a, 0x13, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x54, 0x6f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38,
	0x01, 0x22, 0x56, 0x0a, 0x16, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x50, 0x50, 0x50, 0x6f, 0x45,
	0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x04, 0x63,
	0x6f, 0x6e, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6d, 0x69, 0x6b, 0x72,
	0x6f, 0x74, 0x69, 0x6b, 0x2e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x04, 0x63, 0x6f, 0x6e, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x42, 0x0a, 0x16, 0x43, 0x68, 0x65,
	0x63, 0x6b, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x04, 0x63, 0x6f, 0x6e, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x14, 0x2e, 0x6d, 0x69, 0x6b, 0x72, 0x6f, 0x74, 0x69, 0x6b, 0x2e, 0x43, 0x6f, 0x6e,
	0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x04, 0x63, 0x6f, 0x6e, 0x6e, 0x22, 0x8f, 0x01,
	0x0a, 0x09, 0x50, 0x50, 0x50, 0x6f, 0x45, 0x55, 0x73, 0x65, 0x72, 0x12, 0x43, 0x0a, 0x0a, 0x61,
	0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x23, 0x2e, 0x6d, 0x69, 0x6b, 0x72, 0x6f, 0x74, 0x69, 0x6b, 0x2e, 0x50, 0x50, 0x50, 0x6f, 0x45,
	0x55, 0x73, 0x65, 0x72, 0x2e, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x52, 0x0a, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73,
	0x1a, 0x3d, 0x0a, 0x0f, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22,
	0x37, 0x0a, 0x0a, 0x50, 0x50, 0x50, 0x6f, 0x45, 0x55, 0x73, 0x65, 0x72, 0x73, 0x12, 0x29, 0x0a,
	0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6d,
	0x69, 0x6b, 0x72, 0x6f, 0x74, 0x69, 0x6b, 0x2e, 0x50, 0x50, 0x50, 0x6f, 0x45, 0x55, 0x73, 0x65,
	0x72, 0x52, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x22, 0x3e, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x18,
	0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0xc3, 0x03, 0x0a, 0x0f, 0x4d, 0x69, 0x6b,
	0x72, 0x6f, 0x54, 0x69, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x47, 0x0a, 0x0e,
	0x47, 0x65, 0x74, 0x50, 0x50, 0x50, 0x6f, 0x45, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x12, 0x1f,
	0x2e, 0x6d, 0x69, 0x6b, 0x72, 0x6f, 0x74, 0x69, 0x6b, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x50, 0x50,
	0x6f, 0x45, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x14, 0x2e, 0x6d, 0x69, 0x6b, 0x72, 0x6f, 0x74, 0x69, 0x6b, 0x2e, 0x50, 0x50, 0x50, 0x6f, 0x45,
	0x55, 0x73, 0x65, 0x72, 0x73, 0x12, 0x42, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x50, 0x50, 0x50, 0x6f,
	0x45, 0x55, 0x73, 0x65, 0x72, 0x12, 0x1d, 0x2e, 0x6d, 0x69, 0x6b, 0x72, 0x6f, 0x74, 0x69, 0x6b,
	0x2e, 0x47, 0x65, 0x74, 0x50, 0x50, 0x50, 0x6f, 0x45, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x6d, 0x69, 0x6b, 0x72, 0x6f, 0x74, 0x69, 0x6b, 0x2e,
	0x50, 0x50, 0x50, 0x6f, 0x45, 0x55, 0x73, 0x65, 0x72, 0x12, 0x47, 0x0a, 0x0f, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x50, 0x50, 0x50, 0x6f, 0x45, 0x55, 0x73, 0x65, 0x72, 0x12, 0x20, 0x2e, 0x6d,
	0x69, 0x6b, 0x72, 0x6f, 0x74, 0x69, 0x6b, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x50,
	0x50, 0x6f, 0x45, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12,
	0x2e, 0x6d, 0x69, 0x6b, 0x72, 0x6f, 0x74, 0x69, 0x6b, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x48, 0x0a, 0x0f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x50, 0x50, 0x6f,
	0x45, 0x55, 0x73, 0x65, 0x72, 0x12, 0x20, 0x2e, 0x6d, 0x69, 0x6b, 0x72, 0x6f, 0x74, 0x69, 0x6b,
	0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x50, 0x50, 0x6f, 0x45, 0x55, 0x73, 0x65, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x6d, 0x69, 0x6b, 0x72, 0x6f, 0x74,
	0x69, 0x6b, 0x2e, 0x50, 0x50, 0x50, 0x6f, 0x45, 0x55, 0x73, 0x65, 0x72, 0x12, 0x47, 0x0a, 0x0f,
	0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x50, 0x50, 0x50, 0x6f, 0x45, 0x55, 0x73, 0x65, 0x72, 0x12,
	0x20, 0x2e, 0x6d, 0x69, 0x6b, 0x72, 0x6f, 0x74, 0x69, 0x6b, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76,
	0x65, 0x50, 0x50, 0x50, 0x6f, 0x45, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x12, 0x2e, 0x6d, 0x69, 0x6b, 0x72, 0x6f, 0x74, 0x69, 0x6b, 0x2e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x47, 0x0a, 0x0f, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x43, 0x6f,
	0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x20, 0x2e, 0x6d, 0x69, 0x6b, 0x72, 0x6f,
	0x74, 0x69, 0x6b, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x6d, 0x69, 0x6b,
	0x72, 0x6f, 0x74, 0x69, 0x6b, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x2d,
	0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x79, 0x6f, 0x75,
	0x72, 0x6e, 0x61, 0x6d, 0x65, 0x2f, 0x6d, 0x69, 0x6b, 0x72, 0x6f, 0x74, 0x69, 0x6b, 0x2d, 0x67,
	0x72, 0x70, 0x63, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_proto_mikrotik_proto_rawDescOnce sync.Once
	file_api_proto_mikrotik_proto_rawDescData = file_api_proto_mikrotik_proto_rawDesc
)

func file_api_proto_mikrotik_proto_rawDescGZIP() []byte {
	file_api_proto_mikrotik_proto_rawDescOnce.Do(func() {
		file_api_proto_mikrotik_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_proto_mikrotik_proto_rawDescData)
	})
	return file_api_proto_mikrotik_proto_rawDescData
}

var file_api_proto_mikrotik_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_api_proto_mikrotik_proto_goTypes = []interface{}{
	(*Connection)(nil),             // 0: mikrotik.Connection
	(*GetPPPoEActiveRequest)(nil),  // 1: mikrotik.GetPPPoEActiveRequest
	(*GetPPPoEUserRequest)(nil),    // 2: mikrotik.GetPPPoEUserRequest
	(*CreatePPPoEUserRequest)(nil), // 3: mikrotik.CreatePPPoEUserRequest
	(*UpdatePPPoEUserRequest)(nil), // 4: mikrotik.UpdatePPPoEUserRequest
	(*RemovePPPoEUserRequest)(nil), // 5: mikrotik.RemovePPPoEUserRequest
	(*CheckConnectionRequest)(nil), // 6: mikrotik.CheckConnectionRequest
	(*PPPoEUser)(nil),              // 7: mikrotik.PPPoEUser
	(*PPPoEUsers)(nil),             // 8: mikrotik.PPPoEUsers
	(*Response)(nil),               // 9: mikrotik.Response
	nil,                            // 10: mikrotik.UpdatePPPoEUserRequest.FieldsToUpdateEntry
	nil,                            // 11: mikrotik.PPPoEUser.AttributesEntry
}
var file_api_proto_mikrotik_proto_depIdxs = []int32{
	0,  // 0: mikrotik.GetPPPoEActiveRequest.conn:type_name -> mikrotik.Connection
	0,  // 1: mikrotik.GetPPPoEUserRequest.conn:type_name -> mikrotik.Connection
	0,  // 2: mikrotik.CreatePPPoEUserRequest.conn:type_name -> mikrotik.Connection
	0,  // 3: mikrotik.UpdatePPPoEUserRequest.conn:type_name -> mikrotik.Connection
	10, // 4: mikrotik.UpdatePPPoEUserRequest.fields_to_update:type_name -> mikrotik.UpdatePPPoEUserRequest.FieldsToUpdateEntry
	0,  // 5: mikrotik.RemovePPPoEUserRequest.conn:type_name -> mikrotik.Connection
	0,  // 6: mikrotik.CheckConnectionRequest.conn:type_name -> mikrotik.Connection
	11, // 7: mikrotik.PPPoEUser.attributes:type_name -> mikrotik.PPPoEUser.AttributesEntry
	7,  // 8: mikrotik.PPPoEUsers.users:type_name -> mikrotik.PPPoEUser
	1,  // 9: mikrotik.MikroTikService.GetPPPoEActive:input_type -> mikrotik.GetPPPoEActiveRequest
	2,  // 10: mikrotik.MikroTikService.GetPPPoEUser:input_type -> mikrotik.GetPPPoEUserRequest
	3,  // 11: mikrotik.MikroTikService.CreatePPPoEUser:input_type -> mikrotik.CreatePPPoEUserRequest
	4,  // 12: mikrotik.MikroTikService.UpdatePPPoEUser:input_type -> mikrotik.UpdatePPPoEUserRequest
	5,  // 13: mikrotik.MikroTikService.RemovePPPoEUser:input_type -> mikrotik.RemovePPPoEUserRequest
	6,  // 14: mikrotik.MikroTikService.CheckConnection:input_type -> mikrotik.CheckConnectionRequest
	8,  // 15: mikrotik.MikroTikService.GetPPPoEActive:output_type -> mikrotik.PPPoEUsers
	7,  // 16: mikrotik.MikroTikService.GetPPPoEUser:output_type -> mikrotik.PPPoEUser
	9,  // 17: mikrotik.MikroTikService.CreatePPPoEUser:output_type -> mikrotik.Response
	7,  // 18: mikrotik.MikroTikService.UpdatePPPoEUser:output_type -> mikrotik.PPPoEUser
	9,  // 19: mikrotik.MikroTikService.RemovePPPoEUser:output_type -> mikrotik.Response
	9,  // 20: mikrotik.MikroTikService.CheckConnection:output_type -> mikrotik.Response
	15, // [15:21] is the sub-list for method output_type
	9,  // [9:15] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_api_proto_mikrotik_proto_init() }
func file_api_proto_mikrotik_proto_init() {
	if File_api_proto_mikrotik_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_proto_mikrotik_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Connection); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_mikrotik_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPPPoEActiveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_mikrotik_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPPPoEUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_mikrotik_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePPPoEUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_mikrotik_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatePPPoEUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_mikrotik_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemovePPPoEUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_mikrotik_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckConnectionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_mikrotik_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PPPoEUser); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_mikrotik_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PPPoEUsers); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_mikrotik_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_proto_mikrotik_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_mikrotik_proto_goTypes,
		DependencyIndexes: file_api_proto_mikrotik_proto_depIdxs,
		MessageInfos:      file_api_proto_mikrotik_proto_msgTypes,
	}.Build()
	File_api_proto_mikrotik_proto = out.File
	file_api_proto_mikrotik_proto_rawDesc = nil
	file_api_proto_mikrotik_proto_goTypes = nil
	file_api_proto_mikrotik_proto_depIdxs = nil
}
