// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: mikrotik.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Connection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	User          string                 `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Pass          string                 `protobuf:"bytes,3,opt,name=pass,proto3" json:"pass,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Connection) Reset() {
	*x = Connection{}
	mi := &file_mikrotik_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Connection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Connection) ProtoMessage() {}

func (x *Connection) ProtoReflect() protoreflect.Message {
	mi := &file_mikrotik_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Connection.ProtoReflect.Descriptor instead.
func (*Connection) Descriptor() ([]byte, []int) {
	return file_mikrotik_proto_rawDescGZIP(), []int{0}
}

func (x *Connection) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Connection) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *Connection) GetPass() string {
	if x != nil {
		return x.Pass
	}
	return ""
}

type GetPPPoEActiveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Conn          *Connection            `protobuf:"bytes,1,opt,name=conn,proto3" json:"conn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPPPoEActiveRequest) Reset() {
	*x = GetPPPoEActiveRequest{}
	mi := &file_mikrotik_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPPPoEActiveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPPPoEActiveRequest) ProtoMessage() {}

func (x *GetPPPoEActiveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mikrotik_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPPPoEActiveRequest.ProtoReflect.Descriptor instead.
func (*GetPPPoEActiveRequest) Descriptor() ([]byte, []int) {
	return file_mikrotik_proto_rawDescGZIP(), []int{1}
}

func (x *GetPPPoEActiveRequest) GetConn() *Connection {
	if x != nil {
		return x.Conn
	}
	return nil
}

type GetPPPoEUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Conn          *Connection            `protobuf:"bytes,1,opt,name=conn,proto3" json:"conn,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPPPoEUserRequest) Reset() {
	*x = GetPPPoEUserRequest{}
	mi := &file_mikrotik_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPPPoEUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPPPoEUserRequest) ProtoMessage() {}

func (x *GetPPPoEUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mikrotik_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPPPoEUserRequest.ProtoReflect.Descriptor instead.
func (*GetPPPoEUserRequest) Descriptor() ([]byte, []int) {
	return file_mikrotik_proto_rawDescGZIP(), []int{2}
}

func (x *GetPPPoEUserRequest) GetConn() *Connection {
	if x != nil {
		return x.Conn
	}
	return nil
}

func (x *GetPPPoEUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreatePPPoEUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Conn          *Connection            `protobuf:"bytes,1,opt,name=conn,proto3" json:"conn,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Profile       string                 `protobuf:"bytes,4,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePPPoEUserRequest) Reset() {
	*x = CreatePPPoEUserRequest{}
	mi := &file_mikrotik_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePPPoEUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePPPoEUserRequest) ProtoMessage() {}

func (x *CreatePPPoEUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mikrotik_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePPPoEUserRequest.ProtoReflect.Descriptor instead.
func (*CreatePPPoEUserRequest) Descriptor() ([]byte, []int) {
	return file_mikrotik_proto_rawDescGZIP(), []int{3}
}

func (x *CreatePPPoEUserRequest) GetConn() *Connection {
	if x != nil {
		return x.Conn
	}
	return nil
}

func (x *CreatePPPoEUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreatePPPoEUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreatePPPoEUserRequest) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

type UpdatePPPoEUserRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Conn           *Connection            `protobuf:"bytes,1,opt,name=conn,proto3" json:"conn,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	FieldsToUpdate map[string]string      `protobuf:"bytes,3,rep,name=fields_to_update,json=fieldsToUpdate,proto3" json:"fields_to_update,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdatePPPoEUserRequest) Reset() {
	*x = UpdatePPPoEUserRequest{}
	mi := &file_mikrotik_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePPPoEUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePPPoEUserRequest) ProtoMessage() {}

func (x *UpdatePPPoEUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mikrotik_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePPPoEUserRequest.ProtoReflect.Descriptor instead.
func (*UpdatePPPoEUserRequest) Descriptor() ([]byte, []int) {
	return file_mikrotik_proto_rawDescGZIP(), []int{4}
}

func (x *UpdatePPPoEUserRequest) GetConn() *Connection {
	if x != nil {
		return x.Conn
	}
	return nil
}

func (x *UpdatePPPoEUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdatePPPoEUserRequest) GetFieldsToUpdate() map[string]string {
	if x != nil {
		return x.FieldsToUpdate
	}
	return nil
}

type RemovePPPoEUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Conn          *Connection            `protobuf:"bytes,1,opt,name=conn,proto3" json:"conn,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemovePPPoEUserRequest) Reset() {
	*x = RemovePPPoEUserRequest{}
	mi := &file_mikrotik_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemovePPPoEUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemovePPPoEUserRequest) ProtoMessage() {}

func (x *RemovePPPoEUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mikrotik_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemovePPPoEUserRequest.ProtoReflect.Descriptor instead.
func (*RemovePPPoEUserRequest) Descriptor() ([]byte, []int) {
	return file_mikrotik_proto_rawDescGZIP(), []int{5}
}

func (x *RemovePPPoEUserRequest) GetConn() *Connection {
	if x != nil {
		return x.Conn
	}
	return nil
}

func (x *RemovePPPoEUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CheckConnectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Conn          *Connection            `protobuf:"bytes,1,opt,name=conn,proto3" json:"conn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckConnectionRequest) Reset() {
	*x = CheckConnectionRequest{}
	mi := &file_mikrotik_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckConnectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckConnectionRequest) ProtoMessage() {}

func (x *CheckConnectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mikrotik_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckConnectionRequest.ProtoReflect.Descriptor instead.
func (*CheckConnectionRequest) Descriptor() ([]byte, []int) {
	return file_mikrotik_proto_rawDescGZIP(), []int{6}
}

func (x *CheckConnectionRequest) GetConn() *Connection {
	if x != nil {
		return x.Conn
	}
	return nil
}

type PPPoEUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Uptime        string                 `protobuf:"bytes,3,opt,name=uptime,proto3" json:"uptime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PPPoEUser) Reset() {
	*x = PPPoEUser{}
	mi := &file_mikrotik_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PPPoEUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PPPoEUser) ProtoMessage() {}

func (x *PPPoEUser) ProtoReflect() protoreflect.Message {
	mi := &file_mikrotik_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PPPoEUser.ProtoReflect.Descriptor instead.
func (*PPPoEUser) Descriptor() ([]byte, []int) {
	return file_mikrotik_proto_rawDescGZIP(), []int{7}
}

func (x *PPPoEUser) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PPPoEUser) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *PPPoEUser) GetUptime() string {
	if x != nil {
		return x.Uptime
	}
	return ""
}

type PPPoEUsers struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*PPPoEUser           `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PPPoEUsers) Reset() {
	*x = PPPoEUsers{}
	mi := &file_mikrotik_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PPPoEUsers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PPPoEUsers) ProtoMessage() {}

func (x *PPPoEUsers) ProtoReflect() protoreflect.Message {
	mi := &file_mikrotik_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PPPoEUsers.ProtoReflect.Descriptor instead.
func (*PPPoEUsers) Descriptor() ([]byte, []int) {
	return file_mikrotik_proto_rawDescGZIP(), []int{8}
}

func (x *PPPoEUsers) GetUsers() []*PPPoEUser {
	if x != nil {
		return x.Users
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_mikrotik_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_mikrotik_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_mikrotik_proto_rawDescGZIP(), []int{9}
}

func (x *Response) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_mikrotik_proto protoreflect.FileDescriptor

const file_mikrotik_proto_rawDesc = "" +
	"\n" +
	"\x0emikrotik.proto\x12\bmikrotik\"H\n" +
	"\n" +
	"Connection\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x12\n" +
	"\x04user\x18\x02 \x01(\tR\x04user\x12\x12\n" +
	"\x04pass\x18\x03 \x01(\tR\x04pass\"A\n" +
	"\x15GetPPPoEActiveRequest\x12(\n" +
	"\x04conn\x18\x01 \x01(\v2\x14.mikrotik.ConnectionR\x04conn\"S\n" +
	"\x13GetPPPoEUserRequest\x12(\n" +
	"\x04conn\x18\x01 \x01(\v2\x14.mikrotik.ConnectionR\x04conn\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x8c\x01\n" +
	"\x16CreatePPPoEUserRequest\x12(\n" +
	"\x04conn\x18\x01 \x01(\v2\x14.mikrotik.ConnectionR\x04conn\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x18\n" +
	"\aprofile\x18\x04 \x01(\tR\aprofile\"\xf9\x01\n" +
	"\x16UpdatePPPoEUserRequest\x12(\n" +
	"\x04conn\x18\x01 \x01(\v2\x14.mikrotik.ConnectionR\x04conn\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12^\n" +
	"\x10fields_to_update\x18\x03 \x03(\v24.mikrotik.UpdatePPPoEUserRequest.FieldsToUpdateEntryR\x0efieldsToUpdate\x1aA\n" +
	"\x13FieldsToUpdateEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"V\n" +
	"\x16RemovePPPoEUserRequest\x12(\n" +
	"\x04conn\x18\x01 \x01(\v2\x14.mikrotik.ConnectionR\x04conn\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"B\n" +
	"\x16CheckConnectionRequest\x12(\n" +
	"\x04conn\x18\x01 \x01(\v2\x14.mikrotik.ConnectionR\x04conn\"Q\n" +
	"\tPPPoEUser\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x16\n" +
	"\x06uptime\x18\x03 \x01(\tR\x06uptime\"7\n" +
	"\n" +
	"PPPoEUsers\x12)\n" +
	"\x05users\x18\x01 \x03(\v2\x13.mikrotik.PPPoEUserR\x05users\">\n" +
	"\bResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xc3\x03\n" +
	"\x0fMikroTikService\x12G\n" +
	"\x0eGetPPPoEActive\x12\x1f.mikrotik.GetPPPoEActiveRequest\x1a\x14.mikrotik.PPPoEUsers\x12B\n" +
	"\fGetPPPoEUser\x12\x1d.mikrotik.GetPPPoEUserRequest\x1a\x13.mikrotik.PPPoEUser\x12G\n" +
	"\x0fCreatePPPoEUser\x12 .mikrotik.CreatePPPoEUserRequest\x1a\x12.mikrotik.Response\x12H\n" +
	"\x0fUpdatePPPoEUser\x12 .mikrotik.UpdatePPPoEUserRequest\x1a\x13.mikrotik.PPPoEUser\x12G\n" +
	"\x0fRemovePPPoEUser\x12 .mikrotik.RemovePPPoEUserRequest\x1a\x12.mikrotik.Response\x12G\n" +
	"\x0fCheckConnection\x12 .mikrotik.CheckConnectionRequest\x1a\x12.mikrotik.ResponseB-Z+github.com/yourname/mikrotik-grpc/api/protob\x06proto3"

var (
	file_mikrotik_proto_rawDescOnce sync.Once
	file_mikrotik_proto_rawDescData []byte
)

func file_mikrotik_proto_rawDescGZIP() []byte {
	file_mikrotik_proto_rawDescOnce.Do(func() {
		file_mikrotik_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mikrotik_proto_rawDesc), len(file_mikrotik_proto_rawDesc)))
	})
	return file_mikrotik_proto_rawDescData
}

var file_mikrotik_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_mikrotik_proto_goTypes = []any{
	(*Connection)(nil),             // 0: mikrotik.Connection
	(*GetPPPoEActiveRequest)(nil),  // 1: mikrotik.GetPPPoEActiveRequest
	(*GetPPPoEUserRequest)(nil),    // 2: mikrotik.GetPPPoEUserRequest
	(*CreatePPPoEUserRequest)(nil), // 3: mikrotik.CreatePPPoEUserRequest
	(*UpdatePPPoEUserRequest)(nil), // 4: mikrotik.UpdatePPPoEUserRequest
	(*RemovePPPoEUserRequest)(nil), // 5: mikrotik.RemovePPPoEUserRequest
	(*CheckConnectionRequest)(nil), // 6: mikrotik.CheckConnectionRequest
	(*PPPoEUser)(nil),              // 7: mikrotik.PPPoEUser
	(*PPPoEUsers)(nil),             // 8: mikrotik.PPPoEUsers
	(*Response)(nil),               // 9: mikrotik.Response
	nil,                            // 10: mikrotik.UpdatePPPoEUserRequest.FieldsToUpdateEntry
}
var file_mikrotik_proto_depIdxs = []int32{
	0,  // 0: mikrotik.GetPPPoEActiveRequest.conn:type_name -> mikrotik.Connection
	0,  // 1: mikrotik.GetPPPoEUserRequest.conn:type_name -> mikrotik.Connection
	0,  // 2: mikrotik.CreatePPPoEUserRequest.conn:type_name -> mikrotik.Connection
	0,  // 3: mikrotik.UpdatePPPoEUserRequest.conn:type_name -> mikrotik.Connection
	10, // 4: mikrotik.UpdatePPPoEUserRequest.fields_to_update:type_name -> mikrotik.UpdatePPPoEUserRequest.FieldsToUpdateEntry
	0,  // 5: mikrotik.RemovePPPoEUserRequest.conn:type_name -> mikrotik.Connection
	0,  // 6: mikrotik.CheckConnectionRequest.conn:type_name -> mikrotik.Connection
	7,  // 7: mikrotik.PPPoEUsers.users:type_name -> mikrotik.PPPoEUser
	1,  // 8: mikrotik.MikroTikService.GetPPPoEActive:input_type -> mikrotik.GetPPPoEActiveRequest
	2,  // 9: mikrotik.MikroTikService.GetPPPoEUser:input_type -> mikrotik.GetPPPoEUserRequest
	3,  // 10: mikrotik.MikroTikService.CreatePPPoEUser:input_type -> mikrotik.CreatePPPoEUserRequest
	4,  // 11: mikrotik.MikroTikService.UpdatePPPoEUser:input_type -> mikrotik.UpdatePPPoEUserRequest
	5,  // 12: mikrotik.MikroTikService.RemovePPPoEUser:input_type -> mikrotik.RemovePPPoEUserRequest
	6,  // 13: mikrotik.MikroTikService.CheckConnection:input_type -> mikrotik.CheckConnectionRequest
	8,  // 14: mikrotik.MikroTikService.GetPPPoEActive:output_type -> mikrotik.PPPoEUsers
	7,  // 15: mikrotik.MikroTikService.GetPPPoEUser:output_type -> mikrotik.PPPoEUser
	9,  // 16: mikrotik.MikroTikService.CreatePPPoEUser:output_type -> mikrotik.Response
	7,  // 17: mikrotik.MikroTikService.UpdatePPPoEUser:output_type -> mikrotik.PPPoEUser
	9,  // 18: mikrotik.MikroTikService.RemovePPPoEUser:output_type -> mikrotik.Response
	9,  // 19: mikrotik.MikroTikService.CheckConnection:output_type -> mikrotik.Response
	14, // [14:20] is the sub-list for method output_type
	8,  // [8:14] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_mikrotik_proto_init() }
func file_mikrotik_proto_init() {
	if File_mikrotik_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mikrotik_proto_rawDesc), len(file_mikrotik_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mikrotik_proto_goTypes,
		DependencyIndexes: file_mikrotik_proto_depIdxs,
		MessageInfos:      file_mikrotik_proto_msgTypes,
	}.Build()
	File_mikrotik_proto = out.File
	file_mikrotik_proto_goTypes = nil
	file_mikrotik_proto_depIdxs = nil
}
