// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v4.25.1
// source: mikrotik.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MikroTikService_GetPPPoEActive_FullMethodName  = "/mikrotik.MikroTikService/GetPPPoEActive"
	MikroTikService_GetPPPoEUser_FullMethodName    = "/mikrotik.MikroTikService/GetPPPoEUser"
	MikroTikService_CreatePPPoEUser_FullMethodName = "/mikrotik.MikroTikService/CreatePPPoEUser"
	MikroTikService_UpdatePPPoEUser_FullMethodName = "/mikrotik.MikroTikService/UpdatePPPoEUser"
	MikroTikService_RemovePPPoEUser_FullMethodName = "/mikrotik.MikroTikService/RemovePPPoEUser"
	MikroTikService_CheckConnection_FullMethodName = "/mikrotik.MikroTikService/CheckConnection"
)

// MikroTikServiceClient is the client API for MikroTikService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The main service definition
type MikroTikServiceClient interface {
	GetPPPoEActive(ctx context.Context, in *GetPPPoEActiveRequest, opts ...grpc.CallOption) (*PPPoEUsers, error)
	GetPPPoEUser(ctx context.Context, in *GetPPPoEUserRequest, opts ...grpc.CallOption) (*PPPoEUser, error)
	CreatePPPoEUser(ctx context.Context, in *CreatePPPoEUserRequest, opts ...grpc.CallOption) (*Response, error)
	UpdatePPPoEUser(ctx context.Context, in *UpdatePPPoEUserRequest, opts ...grpc.CallOption) (*PPPoEUser, error)
	RemovePPPoEUser(ctx context.Context, in *RemovePPPoEUserRequest, opts ...grpc.CallOption) (*Response, error)
	CheckConnection(ctx context.Context, in *CheckConnectionRequest, opts ...grpc.CallOption) (*Response, error)
}

type mikroTikServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMikroTikServiceClient(cc grpc.ClientConnInterface) MikroTikServiceClient {
	return &mikroTikServiceClient{cc}
}

func (c *mikroTikServiceClient) GetPPPoEActive(ctx context.Context, in *GetPPPoEActiveRequest, opts ...grpc.CallOption) (*PPPoEUsers, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PPPoEUsers)
	err := c.cc.Invoke(ctx, MikroTikService_GetPPPoEActive_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mikroTikServiceClient) GetPPPoEUser(ctx context.Context, in *GetPPPoEUserRequest, opts ...grpc.CallOption) (*PPPoEUser, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PPPoEUser)
	err := c.cc.Invoke(ctx, MikroTikService_GetPPPoEUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mikroTikServiceClient) CreatePPPoEUser(ctx context.Context, in *CreatePPPoEUserRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, MikroTikService_CreatePPPoEUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mikroTikServiceClient) UpdatePPPoEUser(ctx context.Context, in *UpdatePPPoEUserRequest, opts ...grpc.CallOption) (*PPPoEUser, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PPPoEUser)
	err := c.cc.Invoke(ctx, MikroTikService_UpdatePPPoEUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mikroTikServiceClient) RemovePPPoEUser(ctx context.Context, in *RemovePPPoEUserRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, MikroTikService_RemovePPPoEUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mikroTikServiceClient) CheckConnection(ctx context.Context, in *CheckConnectionRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, MikroTikService_CheckConnection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MikroTikServiceServer is the server API for MikroTikService service.
// All implementations must embed UnimplementedMikroTikServiceServer
// for forward compatibility.
//
// The main service definition
type MikroTikServiceServer interface {
	GetPPPoEActive(context.Context, *GetPPPoEActiveRequest) (*PPPoEUsers, error)
	GetPPPoEUser(context.Context, *GetPPPoEUserRequest) (*PPPoEUser, error)
	CreatePPPoEUser(context.Context, *CreatePPPoEUserRequest) (*Response, error)
	UpdatePPPoEUser(context.Context, *UpdatePPPoEUserRequest) (*PPPoEUser, error)
	RemovePPPoEUser(context.Context, *RemovePPPoEUserRequest) (*Response, error)
	CheckConnection(context.Context, *CheckConnectionRequest) (*Response, error)
	mustEmbedUnimplementedMikroTikServiceServer()
}

// UnimplementedMikroTikServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMikroTikServiceServer struct{}

func (UnimplementedMikroTikServiceServer) GetPPPoEActive(context.Context, *GetPPPoEActiveRequest) (*PPPoEUsers, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPPPoEActive not implemented")
}
func (UnimplementedMikroTikServiceServer) GetPPPoEUser(context.Context, *GetPPPoEUserRequest) (*PPPoEUser, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPPPoEUser not implemented")
}
func (UnimplementedMikroTikServiceServer) CreatePPPoEUser(context.Context, *CreatePPPoEUserRequest) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePPPoEUser not implemented")
}
func (UnimplementedMikroTikServiceServer) UpdatePPPoEUser(context.Context, *UpdatePPPoEUserRequest) (*PPPoEUser, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdatePPPoEUser not implemented")
}
func (UnimplementedMikroTikServiceServer) RemovePPPoEUser(context.Context, *RemovePPPoEUserRequest) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method RemovePPPoEUser not implemented")
}
func (UnimplementedMikroTikServiceServer) CheckConnection(context.Context, *CheckConnectionRequest) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckConnection not implemented")
}
func (UnimplementedMikroTikServiceServer) mustEmbedUnimplementedMikroTikServiceServer() {}
func (UnimplementedMikroTikServiceServer) testEmbeddedByValue()                         {}

// UnsafeMikroTikServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MikroTikServiceServer will
// result in compilation errors.
type UnsafeMikroTikServiceServer interface {
	mustEmbedUnimplementedMikroTikServiceServer()
}

func RegisterMikroTikServiceServer(s grpc.ServiceRegistrar, srv MikroTikServiceServer) {
	// If the following call panics, it indicates UnimplementedMikroTikServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MikroTikService_ServiceDesc, srv)
}

func _MikroTikService_GetPPPoEActive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPPPoEActiveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MikroTikServiceServer).GetPPPoEActive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MikroTikService_GetPPPoEActive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MikroTikServiceServer).GetPPPoEActive(ctx, req.(*GetPPPoEActiveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MikroTikService_GetPPPoEUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPPPoEUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MikroTikServiceServer).GetPPPoEUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MikroTikService_GetPPPoEUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MikroTikServiceServer).GetPPPoEUser(ctx, req.(*GetPPPoEUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MikroTikService_CreatePPPoEUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePPPoEUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MikroTikServiceServer).CreatePPPoEUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MikroTikService_CreatePPPoEUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MikroTikServiceServer).CreatePPPoEUser(ctx, req.(*CreatePPPoEUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MikroTikService_UpdatePPPoEUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePPPoEUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MikroTikServiceServer).UpdatePPPoEUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MikroTikService_UpdatePPPoEUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MikroTikServiceServer).UpdatePPPoEUser(ctx, req.(*UpdatePPPoEUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MikroTikService_RemovePPPoEUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemovePPPoEUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MikroTikServiceServer).RemovePPPoEUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MikroTikService_RemovePPPoEUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MikroTikServiceServer).RemovePPPoEUser(ctx, req.(*RemovePPPoEUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MikroTikService_CheckConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckConnectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MikroTikServiceServer).CheckConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MikroTikService_CheckConnection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MikroTikServiceServer).CheckConnection(ctx, req.(*CheckConnectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MikroTikService_ServiceDesc is the grpc.ServiceDesc for MikroTikService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MikroTikService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mikrotik.MikroTikService",
	HandlerType: (*MikroTikServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPPPoEActive",
			Handler:    _MikroTikService_GetPPPoEActive_Handler,
		},
		{
			MethodName: "GetPPPoEUser",
			Handler:    _MikroTikService_GetPPPoEUser_Handler,
		},
		{
			MethodName: "CreatePPPoEUser",
			Handler:    _MikroTikService_CreatePPPoEUser_Handler,
		},
		{
			MethodName: "UpdatePPPoEUser",
			Handler:    _MikroTikService_UpdatePPPoEUser_Handler,
		},
		{
			MethodName: "RemovePPPoEUser",
			Handler:    _MikroTikService_RemovePPPoEUser_Handler,
		},
		{
			MethodName: "CheckConnection",
			Handler:    _MikroTikService_CheckConnection_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mikrotik.proto",
}
